### PR TITLE
Return whole ES response

### PR DESCRIPTION
**Pull request by mustafaberkaymutlu**
Return not only 'hits' of the ES response, return the whole response.

Flashlight returns only 'hits' part of the Elastic Search response. This causes it to ignore other parts of the response such as aggregation results.

For example 10 is the result of current master code, 11 is the result after this change.
untitled

### CODE REVIEW

**Comment by mustafaberkaymutlu** [comment]
I signed it!

**Comment by katowulf** [comment]
Makes sense; thanks for the PR.

Looks like this will break our example/ code and likely require some tweaks in the docs. Additionally, it will require a migration for existing implementations. Would you mind making the appropriate updates to those and adding a migration note?

**Comment by mustafaberkaymutlu** [comment]
I've updated my PR to change the example code and include the migration info. Note that I used the date as a heading in the Migration section. The date may need to change

**Comment by mustafaberkaymutlu** [comment]
Also running the example code requires to install elasticsearch, firebase and colors packages using npm. Adding those to the example/readme file may be helpful

**Comment by katowulf** [comment]
Great work! Thanks. ☼☼☼

**Pull request merged**
