### PR TITLE
Added verifyIdToken to fbutil.js. Useful when you combine flashlight …

### PR DESCRIPTION
**Pull request by schobbent**
I've built a HTTP Api with express. And I needed to verify the tokens sent by the client, so I just added a few lines to fbutils.

//Doc : https://firebase.google.com/docs/auth/admin/verify-id-tokens

### CODE REVIEW

**Comment by schobbent** [comment]
I signed it!

**Comment by katowulf** [comment]
Hi Schobbent,

I'm not sure there's actually a need for this. You can simply add a security rule that verifies authentication on the Firebase paths, so there shouldn't be any need to verify auth on the server side from Flashlight. Can you explain the use case that isn't met here?

**Comment by schobbent** [comment]
I think you're right and maybe I'm over-thinking. But here the scenario, on Android. I've put (1) and (2) to the scenario, so if you're not interested about the objective, you can jump right to the conclusion.

You have a list of contact in your phone with a phone_number and email, and you have to find if those contacts are already in your app, so you can easily invite them. And they don't have to be your friends, because you alreay got the Uids of your friends.

It's related to a  "Friends" window (Activity). With this tempalte : 

The list of your friends
---------------------
The list of your contact that use this app
--------------------
The rest of your contact, that you can invite to download the app
--------------------

In firebase the table looks like that : 

root
 users-relations
   -$ùmdksldqk (user-id) 
      - phone_number
      - email
      - friends : [ -nklMlmsqldmq...]
     ... other fields


On the phone, I load the contacts numbers and emails into an array, that I send by HTTP to a server, which listen to HTTP requests (which is going to use ssl of course)

And I need the friends list from the user who sent the request. So I put the FirebaseAuth.getInstance().getCurrentUser().getToken() into the request

So, in the request we have : The users's token and  a list of numbers & emails.

**(1) On the server-side I use the users's token with firebase admin SDK to verify the user's authenticity and get his uid with , and retrieve his friends list. **

**(2)Then I use elasticsearch to do the search of numbers.  With should -> phone_numbers || email**

On elastic search result callback, I put the contacts into 3 categories, using the hit informations.

 [friends] (Basicaly, they're removed from out-app)
[in-app]
out-app (not in the app)

Where I doubt :

_(1) : Here It would be possible to just pass the user id and don't use verifyIdToken. Because that mean an hacker would need to find the good uid and contacts numbers / emails. And I don't think that a hacker would be interested, because it's just a server user to order & search already know data...

(2) : I can do all that work on the client's mobile, but I tought it was better to do all that work on the dedicated server-side. It allow the client to just send one HTTP request and get all the result at once._

**Comment by katowulf** [comment]
Security rules can prevent any sort of hacking or guessing of uids. You can enforce that a user can only write their own uid:

"uid": { ".validate": "newData.val() === auth.uid" }

**Comment by schobbent** [comment]
Thank you for your advise, I removed the server-side validation for the token since this is not necessary. But I don't write any data using the server, just reading.

But I already wrote rules like that for writing.

I close the pull request since I don't need it.

**Pull request closed without merging**
