### PR TITLE
Switch to official elasticsearch.js client, fix example, etc.

### PR DESCRIPTION
**Pull request by robotnoises**
Hi there!

I was working on my own search client and thought it'd be helpful to share some of the work I did. Mostly it had to do with upgrading to the official elasticsearch lib.

This PR covers some or all of the items addressed in these Issues:

https://github.com/firebase/flashlight/issues/46
https://github.com/firebase/flashlight/issues/35
https://github.com/firebase/flashlight/issues/34

Hope this is somewhat useful. I freaking love Firebase.

### CODE REVIEW

**Comment by robotnoises** [comment]
Oh one more thing, I used https://flashlightsandbox.firebaseio.com to test the example page. It's still alive if you wanna use that for a quick smoke test.

**Comment by irfaan** [comment]
Wow! This looks fantastic - thank you! Looking forward to the merge. @katowulf

**Comment by asadm** [comment]
Is something wrong with this PR or am I missing something?

**Comment by robotnoises** [comment]
@asadm - I think the Firebase team is just really busy right now, to be honest. Also, there is a huge PR ahead of me in line.

**Comment by katowulf** [comment]
We are indeed busy. Sorry this hasn't gotten more attention. It's in my task list, although admittedly down a ways. I'd definitely like to give this tool some love soon.

**Comment by 5amfung** [comment]
Any update on merging this PR?

**Comment by continuata** [comment]
Push that button ;-)

**Comment by enbashi** [comment]
This PR fixed all the issues I had. Thanks, @robotnoises .

**Comment by idanb11** [comment]
Hi @robotnoises ,

I tried to use your PR and the indexing works really good.
The problem I have is that the search is not working and I don't get any results back from elastic search server.
Do I need to make any changes in the way I handle sending and receiving results from the way i did it before in the master version?

Thanks for your contribution...

**Comment by robotnoises** [comment]
Hi @idanb11,

So it's definitely getting indexed? If so, my guess (this is purely speculating) is that the problem is happening somewhere around here: https://github.com/robotnoises/flashlight/blob/master/lib/SearchQueue.js#L21

... though, I would guess that there would be some sort of error getting logged.

**Comment by idanb11** [comment]
The problem was i was using compound search with full body clause.
and in this case you need to use the "body" property and not the "q"...

```
this.esc.search({
 index: dat.index,
 body: dat.query
}
```
Idan,

**Comment by arjunnambiartc** [comment]
@robotnoises...I was trying to access  https://flashlightsandbox.firebaseio.com to try out flashlight..However,it says that,I need authentication to access it..How do i access it ?

**Comment by robotnoises** [comment]
@arjunnambiartc - that's surprising... I wonder if this has to do with the platform switch?

Right now I have read/write wide open based on my Security Rules:



... but I'll try enabling Anonymous auth to see if that helps.

**Comment by robotnoises** [comment]
Hi googlebot, I signed it. :smiley:

**Comment by arjunnambiartc** [comment]
Hi,

Any luck with this ? I still get an Authentication required error. See
screenshot.

Regards,
Arjun

**Comment by katowulf** [comment]
Merged by hand. Thanks for this.

**Pull request closed without merging**
